### ISSUE TITLE
Update About section content in landing page

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2020#19]
PyCon India Has been happening for past 11 years where in it has grown from few hundread people to thousands of people , our event is very famous of hospitality and food but we will be missing it this year , we assure you there are volunteers who have put in hundreds of hours to bring in an experience which is going to be as close as real world one . Since we will be doing an an online Conference for the first time it too will have our own quirks , but this being an Online conference we can accomodate Pythonistas from around the world right from their  Homes , Offices or wherever they are .

Looking forward to interacting with you all

_Originally posted by @satyaakam in https://github.com/pythonindia/inpycon2020/pull/17_

**Comment by SaptakS** [comment]
> We are going to make a separate explicit about page describing all the decisions and FAQs. This section is just like a teaser excerpt and I would rather keep it short. Planning to put some infographics and further reducing the text in future, and adding a "Read More" link to the more detailed about page.
> 
> The content for the details are at https://docs.google.com/document/d/1_JqWQJQrnOhFbRy0ha6JxvjuFlhwZld6nLn8DDWTHCE/edit?usp=sharing Please feel free to comment. cc: @vipulgupta2048

_Originally commented by @SaptakS in #17_

**Comment by Sc0rpi0n101** [comment]
I think @satyaakam's suggestion would be better suited for the separate about page. Since that content currently contains information about volunteers and motivation etc., the historical context would be a good addition there. 

For the current content, I would suggest a little edit of the original addition, 

 PyCon India is (one of) the largest gathering of Pythonistas in India, and this year we are gathering online! The 12th edition of PyCon India will be taking place online from 2nd October to 5th October 2020. Having to go online due to the current situation, we are planning for the conference to be bigger, better, and more accessible to Pythonistas all over the world from the comfort of their homes.

**Comment by vipulgupta2048** [comment]
PyCon India is the largest gathering of Pythonistas in India for the Python programming language. The 12th edition of PyCon India will be taking place online from 2nd October to 5th October 2020. With this unique scenario at hand, we plan to make this year's conference bigger, better, and more accessible to Pythonistas all across the world who can watch, participate and share their views right from the comfort of their homes. 

How about we go for positivity instead, no use of word `due` if we can help it.

**Comment by Sc0rpi0n101** [comment]
Yours does look better. Although, should we also explicitly state it'll be online this year somewhere?

**Comment by ananyo2012** [comment]
This is done. Closing this.
